from biblioteca import *
p1 = Pessoa("João", 75, 21)
p2 = Pessoa("Madu", 66, 20)
print(p1.nome)
print(p1.peso)
print(p1.idade)
print(p2.nome)
print(p2.peso)
print(p2.idade)
p1.comer()
p1.andar()
p1.dormir()
p2.comer()
p2.andar()
p2.dormir()
